workflows:
  ios-workflow:
    environment:
      xcode: latest
    scripts:
      - name: Tests
        script: |
          xcodebuild clean build test -project BDSwiss/BDSwiss.xcodeproj -scheme "CI" -destination 'platform=iOS Simulator,name=iPhone 14 pro,OS=latest' \ CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO

