workflows:
  ios-workflow:
    environment:
      xcode: latest
    scripts:
      - name: Tests
        script: |
          xcodebuild clean build test -project BDSwiss/BDSwiss.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO

